// <auto-generated />
using System;
using MedEquity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedEquity.Infrastructure.Migrations
{
    [DbContext(typeof(MedEquityDbContext))]
    [Migration("20260221143326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedEquity.Core.Entities.PatientSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("AgeRange")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("age_range");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Geography")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("geography");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.HasKey("SessionId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_patient_sessions_expires_at");

                    b.ToTable("patient_sessions", (string)null);
                });

            modelBuilder.Entity("MedEquity.Core.Entities.Symptom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer")
                        .HasColumnName("duration_hours");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("SymptomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symptom_code");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_symptoms_session_id");

                    b.ToTable("symptoms", null, t =>
                        {
                            t.HasCheckConstraint("ck_symptoms_severity", "severity >= 1 AND severity <= 10");
                        });
                });

            modelBuilder.Entity("MedEquity.Core.Entities.TriageResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("care_level");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("explanation");

                    b.Property<bool>("HumanOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("human_override");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("NurseRationale")
                        .HasColumnType("text")
                        .HasColumnName("nurse_rationale");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("CareLevel")
                        .HasDatabaseName("ix_triage_results_care_level");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_triage_results_created_at");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_triage_results_session_id");

                    b.ToTable("triage_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_triage_results_care_level", "care_level IN ('Emergency', 'UrgentCare', 'PrimaryCare', 'Telemedicine', 'SelfCare')");

                            t.HasCheckConstraint("ck_triage_results_confidence", "confidence >= 0 AND confidence <= 1");
                        });
                });

            modelBuilder.Entity("MedEquity.Core.Entities.Symptom", b =>
                {
                    b.HasOne("MedEquity.Core.Entities.PatientSession", null)
                        .WithMany("Symptoms")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedEquity.Core.Entities.TriageResult", b =>
                {
                    b.HasOne("MedEquity.Core.Entities.PatientSession", null)
                        .WithMany("TriageResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedEquity.Core.Entities.PatientSession", b =>
                {
                    b.Navigation("Symptoms");

                    b.Navigation("TriageResults");
                });
#pragma warning restore 612, 618
        }
    }
}
